export enum Permission {
  PDD_MANAGEMENT = 'PDD_MANAGEMENT',
  COMPANY_MANAGEMENT = 'COMPANY_MANAGEMENT',
  PROJECT_MANAGEMENT = 'PROJECT_MANAGEMENT',
  TOKEN_MANAGEMENT = 'TOKEN_MANAGEMENT',
  USER_MANAGEMENT = 'USER_MANAGEMENT',
  ROLE_MANAGEMENT = 'ROLE_MANAGEMENT',
  REVIEW_REQUEST = 'REVIEW_REQUEST',
}


